Upgrade crypto functions to support OTP 23
apache/couchdb-mochiweb pull request #5
Opened 2021-05-24 17:27 UTC by noahshaw11

Upgrade crypto functions to support OTP 23 to eliminate deprecation warnings during building.

2021-05-24 19:51 UTC, nickva requested changes
Wonder if we could see how much we've diverged from upstream and perhaps make PR against upstream https://github.com/mochi/mochiweb first.

I see upstream uses `platform_define` in rebar to handle compatibility cases: https://github.com/mochi/mochiweb/blob/master/rebar.config#L3-L9. If we went with that theme we might do something like:

```
{platform_define, "^(17|18|19|20|21)", new_crypto_unavailable),
```

Then in `mochiweb_session.erl` we'd add an `-elif` in the existing `crypto_compatibility` `-ifdef`.

```
-ifdef(crypto_compatibility).
 
   crypto:aes_cfb_128_encrypt(Key, IV, Data),
   ...
-elif(new_crypto_unavailable).
   crypto:block_encrypt(aes_cfb128, Key, IV, Data),
   ...
-else. % new crypto available (OTP 22+)
   crypto:crypto_one_time(aes_cfb128, Key, IV, Data, true)
   ...
-endif
```

Also consider adding a few references for some of compatibility changes. Say, a link to docs or some resource describing the differences. Just to help reviewers and to provide documentation

2021-05-25 17:54 UTC, noahshaw11 commented
PR made upstream: https://github.com/mochi/mochiweb/pull/231

2021-05-25 18:32 UTC, noahshaw11 commented on src/mochiweb_socket.erl
> +    Default = filter_unsecure_cipher_suites(ssl:cipher_suites(default, 'tlsv1.3')),
Need to add backward compatibility here.

2021-05-25 18:36 UTC, nickva commented on src/mochiweb_socket.erl
> +    Default = filter_unsecure_cipher_suites(ssl:cipher_suites(default, 'tlsv1.3')),
Also don't forget to add some documentation or references about the API differences. That is, what exactly changed and why the line is needed. I took a quick look at https://erlang.org/doc/man/ssl.html#cipher_suites-2 but couldn't immediately tell. 

To make comparisons easier with older versions, there is https://erldocs.com/. There you can pick an older version of docs and it would be more obvious what has changed.

2021-05-25 19:00 UTC, nickva commented on src/mochiweb_socket.erl
> +    Default = filter_unsecure_cipher_suites(ssl:cipher_suites(default, 'tlsv1.3')),
Also note that the format of the result is different too:

```
16> rp(ssl:cipher_suites(default, 'tlsv1')).
[#{cipher => aes_256_cbc,key_exchange => ecdhe_ecdsa,
   mac => sha,prf => default_prf},
 #{cipher => aes_256_cbc,key_exchange => ecdhe_rsa,mac => sha,
   prf => default_prf},
```

```
19> rp(ssl:cipher_suites()).
[{any,aes_256_gcm,aead,sha384},
 {any,aes_128_gcm,aead,sha256},
 {any,chacha20_poly1305,aead,sha256},
 {any,aes_128_ccm,aead,sha256},
```

2021-05-26 18:31 UTC, nickva commented on src/mochiweb_socket.erl
> +    CipherSuitesListMap = ssl:cipher_suites(default, 'tlsv1.3'),
This might not always be true. `tlsv1.3` might not be available. Notice in Erlang 22 on MacOS BigSur:

```
% asdf shell erlang 21.3.8.15
% erl
Erlang/OTP 21 [erts-10.3.5.11] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [hipe]

Eshell V10.3.5.11  (abort with ^G)
1> ssl:versions().
[{ssl_app,"9.2"},
 {supported,['tlsv1.2','tlsv1.1',tlsv1]},
 {supported_dtls,['dtlsv1.2',dtlsv1]},
 {available,['tlsv1.2','tlsv1.1',tlsv1,sslv3]},
 {available_dtls,['dtlsv1.2',dtlsv1]}]

2> ssl:cipher_suites(default, 'tlsv1.3').
** exception error: no function clause matching
                    ssl_cipher:suites('tlsv1.3') (ssl_cipher.erl, line 253)
     in function  ssl:cipher_suites/2 (ssl.erl, line 909)
```

In this case I think we'd want to look at the `versions` options after it had been filtered with `add_safe_protocol_version/1` os maybe switch the order of:

```
            Opts1 = add_unbroken_ciphers_default(Opts ++ SslOpts),
            Opts2 = add_safe_protocol_versions(Opts1)
```
to
```
            Opts1 = add_safe_protocol_versions(Opts)
            Opts2 = add_unbroken_ciphers_default(Opts1 ++ SslOpts),
```

Then query `ssl:cipher_suites(default, Version)` for each Version and gather the suites in a list that way.

2021-05-26 18:33 UTC, nickva commented on rebar.config
> +            {platform_define, "^(R14|R15|R16|17|18|19|20)", new_ssl_unavailable},
Technically I think cipher suites results as maps became available in 20.

```
% asdf shell erlang 20.3.8.26
% erl
Erlang/OTP 20 [erts-9.3.3.15] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:10] [hipe] [kernel-poll:false]

Eshell V9.3.3.15  (abort with ^G)
> ssl:cipher_suites(default, 'tlsv1.1').
[#{cipher => aes_256_cbc,key_exchange => ecdhe_ecdsa,
```

2021-05-26 18:49 UTC, nickva commented on src/mochiweb_socket.erl
> +    [{ciphers, Ciphers} | proplists:delete(ciphers, Opts)].
This is a bit tricky. I wonder if connect method on 23 (where ` ssl:cipher_suites/0` return tuples) would accept ciphers in a tuple format for the connect method. On 24 it might not. So if we always translate them to tuples, it might not work. 

I wonder if we can filter both tuples and maps with a few changes and pass in maps on Erlang 20+ and handle tuples on Erlang < 20.

I think for `case proplists:get_value(ssl_app, ssl:versions()) of "5.3" ++ _ ...` we don't have to worry about as ssh app version 5.3 only accepts tuples. Erlang 20 has ssl app version as 8.2.x.x.

`filter_unsecure_cipher_suites(Ciphers) ->` could be handled by adding extra clauses to the fun:

```
(#{key_exchange := des_cbc}) -> false;
(#{mac := md5}) -> false;
```

With a comment saying we are filtering both old style tuple cipher suites and new map ones

2021-05-26 18:59 UTC, nickva commented on src/mochiweb_socket.erl
> +    [{ciphers, Ciphers} | proplists:delete(ciphers, Opts)].
It looks like technically ssl:connect/2,3.. would accept tuples as cipher suites even until OTP 25 at least.

https://github.com/erlang/otp/blob/master/lib/ssl/src/ssl.erl#L2580-L2582

But it's still probably better to switch to maps on versions of erlang which support maps.

2021-05-26 19:35 UTC, nickva commented on src/mochiweb_socket.erl
> +    [{version, Versions}] = Opts,
`Opts` would be a proplist and may have multiple items so would have to do:

```
Versions = proplists:get(versions, Opts)
```

And with a comment that we rely on having called `add_safe_protocol_versions/1` which ensures we'll have a `{versions, _}` tuple present.

2021-05-26 19:37 UTC, nickva commented on src/mochiweb_socket.erl
> +    CipherSuites = [ssl:cipher_suites(default, Version) || Version <- Versions],
This will be a list of lists I think. You can calls lists:append/1 on it I think:

```
2> lists:append([[1,2],[3,4]]).
[1,2,3,4]
```

2021-05-26 20:34 UTC, nickva commented on src/mochiweb_socket.erl
> +                    (#{mac := md5}) -> false
These lines should be moved above the (_) "catchall" case. Otherwise the (_) will match first.

2021-05-27 16:31 UTC, nickva commented
@noahshaw11 I think I might have figured one error for Erlang 20.  It looks like `ssl:cipher_suites/2,3` was added later in the Erlang 20 release cycle (20.3) but Travis CI is running Erlang 20. So I think for 20 we can probably move back to using 21 as the earliest release where new ssl is available.

2021-05-27 16:48 UTC, nickva commented on rebar.config
> +            {platform_define, "^(17|18|19|20|21)", new_crypto_unavailable},
Notice that we're declaring that new_crypto_unavailable is true for 14, 15, 16 here! So that means it will try to use the new functions on the really old libraries

2021-05-27 17:16 UTC, noahshaw11 commented on rebar.config
> +            {platform_define, "^(17|18|19|20|21)", new_crypto_unavailable},
Is 14, 15, 16, not covered by the `-ifdef(crypto_compatibility)` statement since it is in an `if/else` block?

2021-05-27 18:50 UTC, nickva commented on rebar.config
> +            {platform_define, "^(17|18|19|20|21)", new_crypto_unavailable},
Good point!

2021-05-27 22:46 UTC, nickva commented
Saw another failure in 22.0
```
::{function_clause,[{dtls_v1,corresponding_tls_version,
                             ['tlsv1.3'],
                             [{file,"dtls_v1.erl"},{line,55}]},
                    {dtls_v1,all_suites,1,[{file,"dtls_v1.erl"},{line,41}]},
                    {ssl,cipher_suites,2,[{file,"ssl.erl"},{line,987}]},
```

I verified it with my own build of 22.0:
```
17> Vers = proplists:get_value(available, ssl:versions()).
['tlsv1.3','tlsv1.2','tlsv1.1',tlsv1,sslv3]
18> catch ssl:cipher_suites(default, 'tlsv1.3').
{'EXIT',{function_clause,[{ssl_cipher,suites,
                                      ['tlsv1.3'],
                                      [{file,"ssl_cipher.erl"},{line,276}]},
                          {ssl,cipher_suites,2,[{file,"ssl.erl"},{line,987}]},
                          {erl_eval,do_apply,6,[{file,"erl_eval.erl"},{line,684}]},
                          {erl_eval,expr,5,[{file,"erl_eval.erl"},{line,437}]},
                          {shell,exprs,7,[{file,"shell.erl"},{line,686}]},
                          {shell,eval_exprs,7,[{file,"shell.erl"},{line,642}]},
                          {shell,eval_loop,3,[{file,"shell.erl"},{line,627}]}]}}
```

And noticed in later versions of 22 like 22.3.4.16 it works...:

```
3> _ = ssl:cipher_suites(default, 'tlsv1.3'), ok.
ok
```

So maybe we'd just end up using the same `new_crypto_unavailable` macro instead of the `new_ssl_available` as both seem to point to 23 being the cutoff release which handle new cipher and new crypto properly. 

It seems that map-based cipher suites are supported in 20-21, and higher versions of 22, but in 22.0 the `ssl:cipher_suites(all | default, Version)` would sometimes fail. To avoid doing fine-grained special cases we might just make 23 the smallest version and call it a day.

But that means we would like to add 23 to the list of tests and hopefully soon enough Travis CI would add 24 to some repos too.

2021-05-28 15:35 UTC, nickva commented
Another hurdle! The problem is rebar was compiled on a too old version of Erlang OTP. Usually those should work with future versions but at some point they would break like you saw. To test locally you might do:

```
rm ./rebar ; rebar get-deps && rebar compile && rebar eunit
```

And then install your own rebar bootstrapped from scratch from https://github.com/rebar/rebar.git then run `./bootstrap` and link to or copy the rebar in your $PATH somewhere

2021-05-29 02:44 UTC, nickva commented on src/mochiweb_session.erl
> +-else. % new crypto available (OTP 22+)
It is 22 technically but we started with 23

2021-06-01 15:35 UTC, nickva commented on src/mochiweb_socket.erl
> +                    ({_,_,md5}) -> false;
Probably don't need to check for tuples here if this block is included in the `-else. ...` section with the new new crypto.

2021-06-01 16:08 UTC, nickva commented on src/mochiweb_socket.erl
> +
Minor nit, let's improve indentation a bit. Something like perhaps?:

```erlang
ssl:filter_cipher_suites(Ciphers, [
    {key_exchange, fun(des_cbc) -> false; (_) -> true end},
    {mac, fun(md5) -> false; (_) -> true end}
]).

2021-06-04 18:22 UTC, noahshaw11 commented
PR was merged upstream: https://github.com/mochi/mochiweb/pull/231

2021-06-04 18:22 UTC, closed without merging